---
title: "home assiqnment 1"
author: "Samuli Saarinen"
date: "2023-11-30"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data import and packages, message=FALSE, warning=FALSE, include=FALSE}
library(readr)
library(varhandle)
library(dplyr)
library(lubridate)
library(car)
library(lmtest)
library(ivreg)
library(writexl)
library(psych)
library(readxl)
library(tseries)
library(stargazer)
library(modelsummary)

options(scipen=999)

GME <- read_csv("GME.csv", col_types = cols(Date = col_date(format = "%m/%d/%Y")))
BBY <- read_csv("BBY.csv", col_types = cols(Date = col_date(format = "%m/%d/%Y")))
index <- read_csv("index.csv", col_types = cols(Date = col_date(format = "%m/%d/%Y")))
industry <- read_csv("industry.csv", col_types = cols(Date = col_date(format = "%m/%d/%Y")))

rocket <- read_excel("rocket.xlsx")
```

```{r data cleaning, message=FALSE, warning=FALSE, include=FALSE}
GME$`Change %` <- as.factor(GME$`Change %`)
GME$`Change %` <- varhandle::unfactor(GME$`Change %`)
GME$`Change %` <- gsub("%", "",GME$`Change %`)
GME$`Change %` <- gsub(",", ".",GME$`Change %`)
GME$`Change %` <- as.numeric(GME$`Change %`)/100

BBY$`Change %` <- as.factor(BBY$`Change %`)
BBY$`Change %` <- varhandle::unfactor(BBY$`Change %`)
BBY$`Change %` <- gsub("%", "",BBY$`Change %`)
BBY$`Change %` <- gsub(",", ".",BBY$`Change %`)
BBY$`Change %` <- as.numeric(BBY$`Change %`)/100

index$`Change %` <- as.factor(index$`Change %`)
index$`Change %` <- varhandle::unfactor(index$`Change %`)
index$`Change %` <- gsub("%", "",index$`Change %`)
index$`Change %` <- gsub(",", ".",index$`Change %`)
index$`Change %` <- as.numeric(index$`Change %`)/100

industry$`Change %` <- as.factor(industry$`Change %`)
industry$`Change %` <- varhandle::unfactor(industry$`Change %`)
industry$`Change %` <- gsub("%", "",industry$`Change %`)
industry$`Change %` <- gsub(",", ".",industry$`Change %`)
industry$`Change %` <- as.numeric(industry$`Change %`)/100
```

```{r creating dataset}
data <- data.frame(BBY$Date)
data <- data %>%
  select("date" = BBY.Date)
data$date <- ymd(data$date)

data$BBY <- BBY$`Change %`
data$GME <- GME$`Change %`
data$index <- index$`Change %`
data$industry <- industry$`Change %`

data_info <- describe(rocket)
data_info
write_xlsx(data_info, "C:\\Users\\ssaar\\Desktop\\Universities\\Taltech\\Econometrics\\econometrics homework\\data_info.xlsx")


```

```{r regressions}
modelGME <- lm(data$GME ~ data$index + data$industry)
summary(modelGME)

modelBBY <- lm(data$BBY ~ data$index + data$industry)
summary(modelBBY)
stargazer(modelGME,modelBBY, type = "html",style = "all2", out = "GME.html")
modelrocket <- lm(rocket$GME ~ rocket$private_information)
summary(modelrocket)
stargazer(modelrocket, type = "html",style = "all2", out = "rocket.html")

iv_model<- ivreg(GME ~  private_information| industry + market, data = rocket)
summary(iv_model)
modelsummary(iv_model, metrics = "all")
```

```{r Accrual Check for multicollinearity}
cor(rocket[c("private_information", "BBY", "GME", "market", "industry")]) # check correlation between independent variables
vif(lm(data$GME ~ data$index + data$industry)) # calculate VIF values
vif(lm(GME ~  private_information + industry + market, data = rocket)) # calculate VIF values

```
```{r durbinwatson }
durbinWatsonTest(lm(GME ~  private_information + industry + market, data = rocket))

durbinWatsonTest(lm(data$GME ~ data$index + data$industry))

jarque.bera.test(rocket$private_information)
jarque.bera.test(rocket$BBY)
jarque.bera.test(rocket$GME)
jarque.bera.test(rocket$market)
jarque.bera.test(rocket$industry)

```

